on:
  schedule:
    - cron: "*/30 * * * *"

name: github_relationship

jobs:
  check:
    name: github_relationship
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo |  ./bin ${{ github.actor }}
      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: commit README
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m 'update README.md'
          git push origin master
        if: steps.diff.outcome == 'failure'
